### ISSUE TITLE
Crash On Dedicated Server

### ISSUE THREAD

**Issue by ChloeDawn** [the-realest-stu/Nether-Chest#2]
Crash when loading the world on a dedicated server.

`java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer`

**Mod version:** [0.2](https://minecraft.curseforge.com/projects/nether-chest/files/2442602)
**Forge version:** [1.12-14.21.1.2387](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2387/forge-1.12-14.21.1.2387-changelog.txt)

**Crash report:** [gist/905688f9d1ec632c81c1284f4a0a3900](https://gist.github.com/InsomniaKitten/905688f9d1ec632c81c1284f4a0a3900)

**Comment by cadaverous-eris** [comment]
Fixed. Building the update now, will release it right after.
